org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.2)
neo_version=21.1.169
neo_version_range=[21.0.118-beta,)
loader_version_range=[4,)
forge_version_range=[47,)
jei_version=19.27.0.340
patchouli_version=92-NEOFORGE-SNAPSHOT

mod_id=feywild
mod_name=Feywild
mod_license=MIT
mod_version=5.4.0
mod_group_id=com.saphienyako.feywild
mod_authors=SaphieNyako
mod_description=Feywild Mod.