org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.19.2
minecraft_version_range=[1.19.2,1.21)
forge_version=43.2.0
forge_version_range=[43,)
loader_version_range=[43,)
mapping_channel=parchment
mapping_version=2022.11.27-1.19.2

mod_id=feywild
mod_name=Feywild
mod_license= MIT
mod_version=5.5.3
mod_group_id=com.saphienyako.feywild
mod_authors=SaphieNyako
mod_description=Feywild Mod.

jei_version=11.6.0.1014